// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: tg-dis.proto

package telegram_discord_bridge

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TgdisMessageService_NewMessage_FullMethodName = "/tgdis.TgdisMessageService/NewMessage"
)

// TgdisMessageServiceClient is the client API for TgdisMessageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TgdisMessageServiceClient interface {
	NewMessage(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageResponse, error)
}

type tgdisMessageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTgdisMessageServiceClient(cc grpc.ClientConnInterface) TgdisMessageServiceClient {
	return &tgdisMessageServiceClient{cc}
}

func (c *tgdisMessageServiceClient) NewMessage(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageResponse)
	err := c.cc.Invoke(ctx, TgdisMessageService_NewMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TgdisMessageServiceServer is the server API for TgdisMessageService service.
// All implementations must embed UnimplementedTgdisMessageServiceServer
// for forward compatibility.
type TgdisMessageServiceServer interface {
	NewMessage(context.Context, *MessageRequest) (*MessageResponse, error)
	mustEmbedUnimplementedTgdisMessageServiceServer()
}

// UnimplementedTgdisMessageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTgdisMessageServiceServer struct{}

func (UnimplementedTgdisMessageServiceServer) NewMessage(context.Context, *MessageRequest) (*MessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewMessage not implemented")
}
func (UnimplementedTgdisMessageServiceServer) mustEmbedUnimplementedTgdisMessageServiceServer() {}
func (UnimplementedTgdisMessageServiceServer) testEmbeddedByValue()                             {}

// UnsafeTgdisMessageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TgdisMessageServiceServer will
// result in compilation errors.
type UnsafeTgdisMessageServiceServer interface {
	mustEmbedUnimplementedTgdisMessageServiceServer()
}

func RegisterTgdisMessageServiceServer(s grpc.ServiceRegistrar, srv TgdisMessageServiceServer) {
	// If the following call pancis, it indicates UnimplementedTgdisMessageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TgdisMessageService_ServiceDesc, srv)
}

func _TgdisMessageService_NewMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TgdisMessageServiceServer).NewMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TgdisMessageService_NewMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TgdisMessageServiceServer).NewMessage(ctx, req.(*MessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TgdisMessageService_ServiceDesc is the grpc.ServiceDesc for TgdisMessageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TgdisMessageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tgdis.TgdisMessageService",
	HandlerType: (*TgdisMessageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewMessage",
			Handler:    _TgdisMessageService_NewMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tg-dis.proto",
}
